server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
      routes:
        - id: producto-service
          uri: lb://producto-service
          predicates:
            - Path=/productos/**
          filters:
            - StripPrefix=0   # 👈 mantiene /productos en la URL
        - id: carrito-service
          uri: lb://carrito-service
          predicates:
            - Path=/carrito/**
          filters:
            - StripPrefix=0
        - id: venta-service
          uri: lb://venta-service
          predicates:
            - Path=/venta/**
          filters:
            - StripPrefix=0
